CREATE TABLE "order" (
ORDER_ID VARCHAR (50) PRIMARY KEY,
USER_ID VARCHAR (50) NOT NULL,
SHOP_ID VARCHAR (50) NOT NULL,
ORIGINAL_PRICE DECIMAL NOT NULL,
DISCOUNT VARCHAR (50),
DISCOUNT_AMOUNT DECIMAL,
TOTAL_PRICE DECIMAL NOT NULL,
QUEUE_ID INTEGER NOT NULL,
STATUS VARCHAR (50) NOT NULL,
CREATED_AT BIGINT NOT NULL,
CREATED_BY VARCHAR (50),
UPDATED_AT BIGINT,
UPDATED_BY VARCHAR (50),
estimate_finish_time bigint
);

create TABLE ORDER_ITEMS (
ORDER_ITEM_ID VARCHAR (50) PRIMARY KEY,
ITEM_ID VARCHAR (50) NOT NULL,
ORDER_ID VARCHAR (50) ,
QUANTITY INTEGER NOT NULL,
ORIGINAL_PRICE DECIMAL NOT NULL,
DISCOUNT VARCHAR (50),
DISCOUNT_AMOUNT DECIMAL,
PRICE DECIMAL NOT NULL,
NOTE varchar(500),
CREATED_AT BIGINT NOT NULL,
CREATED_BY VARCHAR (50),
UPDATED_AT BIGINT ,
UPDATED_BY VARCHAR (50)
);